spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: TRANSFERS-SERVICE
          uri: lb://TRANSFERS-SERVICE
          predicates:
            - Path=/transfers/**
        - id: PLAYERTEAM-SERVICE
          uri: lb://PLAYERTEAM-SERVICE
          predicates:
            - Path=/players/**
        - id: PLAYERTEAM-SERVICE
          uri: lb://PLAYERTEAM-SERVICE
          predicates:
            - Path=/teams/**
        - id: PLAYERTEAM-SERVICE
          uri: lb://PLAYERTEAM-SERVICE
          predicates:
            - Path=/contracts/**
server:
  port: 9191

