spring:
  application:
    name: TRANSFERS-SERVICE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/player_market
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8081

